language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
	provider: heroku
	app: project1-travis
	on: master
	skip_cleanup: true
	api_key:
	secure: msWnoUf7PAvWn8lUl0AQ5CbvrpYpsZLoB2Sv5A7GdxgAkBgkJcVxWVqCZoGpCaGpEpSEcgywwy7QMJ0p2Fu3PHJCxbXLVpJqI1zGl3DgbNGIivWzT+mRcn0cweiMNGLuxpgyVVgW5OFZ3d4e+kBLaf1LAVfPvQ+FJr3o7XjB0Y6rHsndR6AQinJVIlZIVW0//5Nac/DnfLK1euYxIBjbQMxLJHJN3UGwdEJtd8S9il0ZwhN6rwToEYOV1a1jvVQBsjESx/cigkv9JETi3Ztn97/sbtY5mXatqMiIw595CdLHbjkyoayT60Ktg+dQRUaPtNyGRYaLaOslmgMplMDbLLA6fpWdNtd9m6JoeMjJ8PrLbs8njyce0JSW26s1J8o2we3VxcU/4kXlMkjHuBwb83/BHe1O+sqwbzTNXicruDBvMz4gOpid4Omq3+imOFwqyzdvLS489EJ/I2OP2rMfdyykG8oPhhMA93JwOH0I2DQ73Z8jmz1UtiTYd8XBo95XAcjM/0vK/sBd9phsw0p3DLS/RwzSTO4FefMoOAcoikl2ZTfwVtRsLkhc1KT4Lmz9IrytYdZxiBZ4rrMGexjMyYP5Z5f65V+oB61W4ud2Xo6va8+xNvKYpfwBai4kYKjNFDcrWjbYMLCsQVdUYNs2YEqCenaXXgLiLrp6SaDcwKY=
