language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
provider: heroku
app: alexdaw-project1-travis
on: master
skip_cleanup: true
api_key:
secure: fMoUM5Zw1exkRmajrwActQyV2KgRsu+26nSHnk+eP0IYCBGtsytgufMUYZ1o8LF0MzMsAQoD+ZqoIrjZyvGobUq+67e3l+u8Uv5oj8++grdLCrnZuNatKYPZdw+HkVax+N6aY7yjRy6dqk+oltj6TCPsqdk1rFiSeMrhin76UmswGzLzzoxYJ5+s/nviIWhtdLs7FhhPVbNaRAtiARgyUAeElr0VaoWl/9LBYByOVI2p8cvOWRlp6/dH6Qbrz8K+EUMYyOHT8wpFDHR18C5YjvOMLtQ6j41dgthGgnO7Gf+lq8O6sqVmy9NUlH45MkR8tfkKDfyv32nz3ICDCWjOp8yoQALMlN/uUyJNmRAtaRKEGhmAgFIy4rLl5+uH61IuYkYD2fJOVukyEZeOEfwlVkfp/RTw5dx6ltTcThH8De8DGiCQuS7EaOoHRVRCxn1HcFjNmppojxnohS/s+5LefhvQqBGYbLZVdtVmMW2bEWgf2DT6ikDaG/ejduVHS7ayOJuMREydyAy9zT5QFR+U0Plxbk7Kf92pYScsk8OuG8Czkr909G0gKJ+tgr0XHwGOoZ3sMVwAJfLfLB4+lTQxRjCBz/+sueFoZDVdnNHyRk265nlDmHhkJ3ruz66S+Z1AJdEbGxHyN4x7j2JEm9btXIyRnG4R1i89PIchAqIZUQk=
